version: 3

pullapprove_conditions:
- condition: "base.ref == 'master'"
  unmet_status: success
  explanation: "Review not required unless merging to master"

groups:
  admins:
    conditions:
    - "base.ref == 'master'"
    reviewers:
      teams:
      - code-admins
    reviews:
      required: 1
      request: 1
      request_order: shuffle
